### ISSUE TITLE
clang: error: the clang compiler does not support '-march=nehalem'

### ISSUE THREAD

**Issue by liuxinxaut** [SwiftXcode/homebrew-swiftxcode#2]
I use Homebrew install swiftNIO2 occured an ERROR: 
------------------------------------------------------------------------------------------
`clang: error: the clang compiler does not support '-march=nehalem'

** BUILD FAILED **

The following build commands failed:
	CompileC /tmp/swift-progress-20210429-21539-1f7wzd9/swift-progress-0.9.2/build/DerivedData/Build/Intermediates.noindex/swift-progress.build/Release/swift-progress.build/Objects-normal/arm64/main.o /tmp/swift-progress-20210429-21539-1f7wzd9/swift-progress-0.9.2/Sources/swift-progress/main.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [build/DerivedData/Build/Products/Release/swift-progress] Error 65`
------------------------------------------------------------------------------------------

My PC Environment is macOS Big Sur 11.3 ,Swift-5.4
-------------------------
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
-------------------------

thank you for all to resolving this error .
you have my appreciation.

Did anyone has issue like this and  how to resolved ?

**Comment by helje5** [comment]
Xcode now has builtin support for SPM packages, swift-xcode is now superfluous and hasn't been tested w/ late Xcode's.

Summary: Just use Xcode :-)

**Comment by liuxinxaut** [comment]
> Xcode now has builtin support for SPM packages, swift-xcode is now superfluous and hasn't been tested w/ late Xcode's.
> 
> Summary: Just use Xcode :-)

Thank you !! :-)
